### PR TITLE
Make changes for ActiveRecord

### PR DESCRIPTION
**Pull request by JacobEvelyn**
I figured out a way to make it work with ActiveRecord and generic Ruby classes alike! The downside is there's some complex metaprogramming but fortunately it's isolated and won't affect anything adversely.

### CODE REVIEW

**Comment by JacobEvelyn** [comment]
Once this merges I'll yank the version from RubyGems and push the new version.

**Comment by JacobEvelyn** [comment]
Just a friendly nudge that this needs review, @radhikamalik. We can't use this in our code until this goes through.

**Comment by radhikamalik** [comment]
Whoops, sorry about that. Reviewing now. Can we create JIRA tasks for this repo too so we don't lose task tracking? :)

**Comment by JacobEvelyn** [comment]
I'm a little wary of duplicating all GitHub issues in JIRA because I think they'll quickly get out of sync. But I'm not strongly against it; let's bring this up in standup on Monday.

**Comment by JacobEvelyn** [comment]
Back to you!

**Comment by radhikamalik** [comment]
LGTM

**Comment by JacobEvelyn** [comment]
Thanks!

**Pull request merged**
